
eureka:
  instance:
    appname: user-microservice
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

rabbitmq:
  host: localhost
  port: 5672
  username: user
  password: password